// ✅ Tek kaynak: default kategoriler (CategoryGrid + BizApplyForm)
export const TG_DEFAULT_CATEGORIES = [
  { key: "Avukatlar", icon: "law" },
  { key: "Doktorlar & Sağlık Hizmetleri", icon: "health" },
  { key: "Restoranlar", icon: "restaurant" },
  { key: "Emlak Hizmetleri", icon: "realestate" },
  { key: "Araç Hizmetleri", icon: "autoservice" },
  { key: "Kuaförler", icon: "salon" },
  { key: "Berberler", icon: "barber" },
  { key: "Araç Kiralama", icon: "rental" },
  { key: "Araç Bayileri", icon: "dealership" },
  { key: "Türk Marketleri", icon: "market" },
  { key: "Okullar & Eğitim Hizmetleri", icon: "education" },
  { key: "Tamir Ustası / Ev Hizmetleri", icon: "handyman" },
  { key: "Temizlik Hizmetleri", icon: "cleaning" },
];

// ✅ Telefon ülke kodları (liste büyütülebilir)
export const TG_PHONE_CODES = [
  { country: "United States", code: "US", dial: "+1" },
  { country: "Canada", code: "CA", dial: "+1" },
  { country: "Turkey", code: "TR", dial: "+90" },
  { country: "United Kingdom", code: "GB", dial: "+44" },
  { country: "Germany", code: "DE", dial: "+49" },
  { country: "France", code: "FR", dial: "+33" },
  { country: "Netherlands", code: "NL", dial: "+31" },
  { country: "Belgium", code: "BE", dial: "+32" },
  { country: "Spain", code: "ES", dial: "+34" },
  { country: "Italy", code: "IT", dial: "+39" },
  { country: "Switzerland", code: "CH", dial: "+41" },
  { country: "Austria", code: "AT", dial: "+43" },
  { country: "Sweden", code: "SE", dial: "+46" },
  { country: "Norway", code: "NO", dial: "+47" },
  { country: "Denmark", code: "DK", dial: "+45" },
  { country: "Finland", code: "FI", dial: "+358" },
  { country: "Ireland", code: "IE", dial: "+353" },
  { country: "Portugal", code: "PT", dial: "+351" },
  { country: "Greece", code: "GR", dial: "+30" },
  { country: "Romania", code: "RO", dial: "+40" },
  { country: "Bulgaria", code: "BG", dial: "+359" },
  { country: "Poland", code: "PL", dial: "+48" },
  { country: "Czechia", code: "CZ", dial: "+420" },
  { country: "Hungary", code: "HU", dial: "+36" },
  { country: "Ukraine", code: "UA", dial: "+380" },
  { country: "Russia", code: "RU", dial: "+7" },
  { country: "Georgia", code: "GE", dial: "+995" },
  { country: "Azerbaijan", code: "AZ", dial: "+994" },
  { country: "United Arab Emirates", code: "AE", dial: "+971" },
  { country: "Saudi Arabia", code: "SA", dial: "+966" },
  { country: "Qatar", code: "QA", dial: "+974" },
  { country: "Kuwait", code: "KW", dial: "+965" },
  { country: "Israel", code: "IL", dial: "+972" },
  { country: "Egypt", code: "EG", dial: "+20" },
  { country: "Morocco", code: "MA", dial: "+212" },
  { country: "Tunisia", code: "TN", dial: "+216" },
  { country: "Algeria", code: "DZ", dial: "+213" },
  { country: "South Africa", code: "ZA", dial: "+27" },
  { country: "India", code: "IN", dial: "+91" },
  { country: "Pakistan", code: "PK", dial: "+92" },
  { country: "Bangladesh", code: "BD", dial: "+880" },
  { country: "China", code: "CN", dial: "+86" },
  { country: "Japan", code: "JP", dial: "+81" },
  { country: "South Korea", code: "KR", dial: "+82" },
  { country: "Singapore", code: "SG", dial: "+65" },
  { country: "Malaysia", code: "MY", dial: "+60" },
  { country: "Indonesia", code: "ID", dial: "+62" },
  { country: "Thailand", code: "TH", dial: "+66" },
  { country: "Vietnam", code: "VN", dial: "+84" },
  { country: "Philippines", code: "PH", dial: "+63" },
  { country: "Australia", code: "AU", dial: "+61" },
  { country: "New Zealand", code: "NZ", dial: "+64" },
  { country: "Mexico", code: "MX", dial: "+52" },
  { country: "Brazil", code: "BR", dial: "+55" },
  { country: "Argentina", code: "AR", dial: "+54" },
  { country: "Chile", code: "CL", dial: "+56" },
  { country: "Colombia", code: "CO", dial: "+57" },
];
